from .user_detail import UserDetailView
from .user_archive import UserArchiveView
from .home import HomeView
from .search_user import SearchUser
from .sign_in import SigninView
from .sign_out import SignOutView
from .follow import FollowView
from .unfollow import UnfollowView
from .edit_profile import UpdateProfileView
from .change_password import ChangePasswordView
from .register import SignupView
